//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVBVer2._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLVBEntities1 : DbContext
    {
        public QLVBEntities1()
            : base("name=QLVBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryVB> CategoryVBs { get; set; }
        public virtual DbSet<tblCVden> tblCVdens { get; set; }
        public virtual DbSet<tblCVdi> tblCVdis { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
    
        public virtual ObjectResult<danhsachCVden_Result> danhsachCVden()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<danhsachCVden_Result>("danhsachCVden");
        }
    
        public virtual ObjectResult<danhsachCVdi_Result> danhsachCVdi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<danhsachCVdi_Result>("danhsachCVdi");
        }
    
        public virtual int DELETECVden(string socongvan)
        {
            var socongvanParameter = socongvan != null ?
                new ObjectParameter("socongvan", socongvan) :
                new ObjectParameter("socongvan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETECVden", socongvanParameter);
        }
    
        public virtual int DELETECVdi(string socongvan)
        {
            var socongvanParameter = socongvan != null ?
                new ObjectParameter("socongvan", socongvan) :
                new ObjectParameter("socongvan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETECVdi", socongvanParameter);
        }
    
        public virtual int THEMCVden(Nullable<System.DateTime> ngaythang, string socongvan, string noidung, string noigui, string nguoiky, Nullable<System.DateTime> ngaychidao, string ykienchidao, string ghichu, string anhscan)
        {
            var ngaythangParameter = ngaythang.HasValue ?
                new ObjectParameter("ngaythang", ngaythang) :
                new ObjectParameter("ngaythang", typeof(System.DateTime));
    
            var socongvanParameter = socongvan != null ?
                new ObjectParameter("socongvan", socongvan) :
                new ObjectParameter("socongvan", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var noiguiParameter = noigui != null ?
                new ObjectParameter("noigui", noigui) :
                new ObjectParameter("noigui", typeof(string));
    
            var nguoikyParameter = nguoiky != null ?
                new ObjectParameter("nguoiky", nguoiky) :
                new ObjectParameter("nguoiky", typeof(string));
    
            var ngaychidaoParameter = ngaychidao.HasValue ?
                new ObjectParameter("ngaychidao", ngaychidao) :
                new ObjectParameter("ngaychidao", typeof(System.DateTime));
    
            var ykienchidaoParameter = ykienchidao != null ?
                new ObjectParameter("ykienchidao", ykienchidao) :
                new ObjectParameter("ykienchidao", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var anhscanParameter = anhscan != null ?
                new ObjectParameter("anhscan", anhscan) :
                new ObjectParameter("anhscan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMCVden", ngaythangParameter, socongvanParameter, noidungParameter, noiguiParameter, nguoikyParameter, ngaychidaoParameter, ykienchidaoParameter, ghichuParameter, anhscanParameter);
        }
    
        public virtual int THEMCVdi(string socongvan, Nullable<System.DateTime> ngaygui, string noidung, string noinhan, string ghichu, string anhscan)
        {
            var socongvanParameter = socongvan != null ?
                new ObjectParameter("socongvan", socongvan) :
                new ObjectParameter("socongvan", typeof(string));
    
            var ngayguiParameter = ngaygui.HasValue ?
                new ObjectParameter("ngaygui", ngaygui) :
                new ObjectParameter("ngaygui", typeof(System.DateTime));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var noinhanParameter = noinhan != null ?
                new ObjectParameter("noinhan", noinhan) :
                new ObjectParameter("noinhan", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var anhscanParameter = anhscan != null ?
                new ObjectParameter("anhscan", anhscan) :
                new ObjectParameter("anhscan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMCVdi", socongvanParameter, ngayguiParameter, noidungParameter, noinhanParameter, ghichuParameter, anhscanParameter);
        }
    
        public virtual ObjectResult<timkiemCVden_Result> timkiemCVden(string searchText, string searchType)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var searchTypeParameter = searchType != null ?
                new ObjectParameter("searchType", searchType) :
                new ObjectParameter("searchType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timkiemCVden_Result>("timkiemCVden", searchTextParameter, searchTypeParameter);
        }
    
        public virtual ObjectResult<timkiemCVdi_Result> timkiemCVdi(string searchText, string searchType)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("searchText", searchText) :
                new ObjectParameter("searchText", typeof(string));
    
            var searchTypeParameter = searchType != null ?
                new ObjectParameter("searchType", searchType) :
                new ObjectParameter("searchType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<timkiemCVdi_Result>("timkiemCVdi", searchTextParameter, searchTypeParameter);
        }
    
        public virtual int UPDATECVden(Nullable<System.DateTime> ngaythang, string socongvan, string noidung, string noigui, string nguoiky, Nullable<System.DateTime> ngaychidao, string ykienchidao, string ghichu, string anhscan)
        {
            var ngaythangParameter = ngaythang.HasValue ?
                new ObjectParameter("ngaythang", ngaythang) :
                new ObjectParameter("ngaythang", typeof(System.DateTime));
    
            var socongvanParameter = socongvan != null ?
                new ObjectParameter("socongvan", socongvan) :
                new ObjectParameter("socongvan", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var noiguiParameter = noigui != null ?
                new ObjectParameter("noigui", noigui) :
                new ObjectParameter("noigui", typeof(string));
    
            var nguoikyParameter = nguoiky != null ?
                new ObjectParameter("nguoiky", nguoiky) :
                new ObjectParameter("nguoiky", typeof(string));
    
            var ngaychidaoParameter = ngaychidao.HasValue ?
                new ObjectParameter("ngaychidao", ngaychidao) :
                new ObjectParameter("ngaychidao", typeof(System.DateTime));
    
            var ykienchidaoParameter = ykienchidao != null ?
                new ObjectParameter("ykienchidao", ykienchidao) :
                new ObjectParameter("ykienchidao", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var anhscanParameter = anhscan != null ?
                new ObjectParameter("anhscan", anhscan) :
                new ObjectParameter("anhscan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATECVden", ngaythangParameter, socongvanParameter, noidungParameter, noiguiParameter, nguoikyParameter, ngaychidaoParameter, ykienchidaoParameter, ghichuParameter, anhscanParameter);
        }
    
        public virtual int UPDATECVdi(Nullable<System.DateTime> ngaygui, string socongvan, string noidung, string noinhan, string ghichu, string anhscan)
        {
            var ngayguiParameter = ngaygui.HasValue ?
                new ObjectParameter("ngaygui", ngaygui) :
                new ObjectParameter("ngaygui", typeof(System.DateTime));
    
            var socongvanParameter = socongvan != null ?
                new ObjectParameter("socongvan", socongvan) :
                new ObjectParameter("socongvan", typeof(string));
    
            var noidungParameter = noidung != null ?
                new ObjectParameter("noidung", noidung) :
                new ObjectParameter("noidung", typeof(string));
    
            var noinhanParameter = noinhan != null ?
                new ObjectParameter("noinhan", noinhan) :
                new ObjectParameter("noinhan", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("ghichu", ghichu) :
                new ObjectParameter("ghichu", typeof(string));
    
            var anhscanParameter = anhscan != null ?
                new ObjectParameter("anhscan", anhscan) :
                new ObjectParameter("anhscan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATECVdi", ngayguiParameter, socongvanParameter, noidungParameter, noinhanParameter, ghichuParameter, anhscanParameter);
        }
    }
}
