//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVBVer2._1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLVBEntities1 : DbContext
    {
        public QLVBEntities1()
            : base("name=QLVBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryVB> CategoryVBs { get; set; }
        public virtual DbSet<tblCVden> tblCVdens { get; set; }
        public virtual DbSet<tblCVdi> tblCVdis { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
    }
}
